# Generated by Django 2.2.5 on 2019-09-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64, verbose_name='Название модели')),
                ('model_price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('model_photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('model_photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 1')),
                ('model_photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 2')),
                ('model_photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 3')),
                ('model_photo_4', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 4')),
                ('model_photo_5', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 5')),
                ('model_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Кроссовок',
                'verbose_name_plural': 'Кроссовки',
            },
        ),
    ]
