# Generated by Django 2.2.5 on 2019-09-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='model_photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 1'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='model_photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 2'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='model_photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 3'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='model_photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 4'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='model_photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Доп. Фото 5'),
        ),
    ]
