# Generated by Django 2.2.5 on 2019-09-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sneakers_model_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='model_date_added',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='model_photo_1',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='model_photo_2',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='model_photo_3',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='model_photo_4',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='model_photo_5',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='model_photo_main',
        ),
    ]
